version: "3"
services:
  db:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=foolog
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:4.0.2-alpine
    ports:
      - "6379:6379"

  ruby:
    build: ./
    tty: true
    volumes:
      - ./:/mnt
    links:
      - db
      - redis
    ports:
      - "3000:3000"
